### ISSUE TITLE
Area personale ADMIN

### ISSUE THREAD

**Issue by CodeUncas** [EliaBergamin/Progetto-TecWeb#61]
Scrivere pagine inserimento MOSTRA, html e css e insert php

**Comment by MilanRiccardo03** [comment]
# Use case:
 - utente loggato come admin entra nell'area personale

# Contenuto
 - [ ] lista mostre
 - [ ] opzione per modificarle 
 - [ ] opzione per eliminarle
 - [ ] opzione per aggiungerne una

**Comment by CodeUncas** [comment]
@Jacky8703 taggami quanto hai finito html e css

**Comment by Jacky8703** [comment]
@CodeUncas tutto tuo, il branch è feature/area_personale_admin

**Comment by CodeUncas** [comment]
fatto chiudo issue
